-- MySQL Script generated by MySQL Workbench
-- Thu Jun  1 18:48:03 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema goit
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `goit` ;

-- -----------------------------------------------------
-- Schema goit
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `goit` DEFAULT CHARACTER SET utf8 ;
USE `goit` ;

-- -----------------------------------------------------
-- Table `goit`.`developers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goit`.`developers` ;

CREATE TABLE IF NOT EXISTS `goit`.`developers` (
  `dev_id` INT NOT NULL AUTO_INCREMENT,
  `dev_name` VARCHAR(16) NOT NULL,
  `dev_lastname` VARCHAR(16) NOT NULL,
  `dev_email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`dev_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goit`.`skills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goit`.`skills` ;

CREATE TABLE IF NOT EXISTS `goit`.`skills` (
  `skill_id` INT NOT NULL AUTO_INCREMENT,
  `skill_skill` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`skill_id`),
  UNIQUE INDEX `skill_skill_UNIQUE` (`skill_skill` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goit`.`projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goit`.`projects` ;

CREATE TABLE IF NOT EXISTS `goit`.`projects` (
  `proj_id` INT NOT NULL AUTO_INCREMENT,
  `proj_name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`proj_id`),
  UNIQUE INDEX `proj_id_UNIQUE` (`proj_id` ASC),
  UNIQUE INDEX `proj_name_UNIQUE` (`proj_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goit`.`companies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goit`.`companies` ;

CREATE TABLE IF NOT EXISTS `goit`.`companies` (
  `company_id` INT NOT NULL AUTO_INCREMENT,
  `company_name` VARCHAR(45) NOT NULL,
  `company_address` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`company_id`),
  UNIQUE INDEX `company_name_UNIQUE` (`company_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goit`.`customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goit`.`customers` ;

CREATE TABLE IF NOT EXISTS `goit`.`customers` (
  `cust_id` INT NOT NULL AUTO_INCREMENT,
  `cust_name` VARCHAR(16) NOT NULL,
  `cust_lastname` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`cust_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goit`.`developers_has_skills`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goit`.`developers_has_skills` ;

CREATE TABLE IF NOT EXISTS `goit`.`developers_has_skills` (
  `developers_id` INT NOT NULL,
  `skills_id` INT NOT NULL,
  PRIMARY KEY (`developers_id`, `skills_id`),
  INDEX `fk_developers_has_skills_skills1_idx` (`skills_id` ASC),
  INDEX `fk_developers_has_skills_developers_idx` (`developers_id` ASC),
  CONSTRAINT `fk_developers_has_skills_developers`
    FOREIGN KEY (`developers_id`)
    REFERENCES `goit`.`developers` (`dev_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_developers_has_skills_skills1`
    FOREIGN KEY (`skills_id`)
    REFERENCES `goit`.`skills` (`skill_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goit`.`companies_has_projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goit`.`companies_has_projects` ;

CREATE TABLE IF NOT EXISTS `goit`.`companies_has_projects` (
  `companies_id` INT NOT NULL,
  `projects_id` INT NOT NULL,
  PRIMARY KEY (`companies_id`, `projects_id`),
  INDEX `fk_companies_has_projects_projects1_idx` (`projects_id` ASC),
  INDEX `fk_companies_has_projects_companies1_idx` (`companies_id` ASC),
  CONSTRAINT `fk_companies_has_projects_companies1`
    FOREIGN KEY (`companies_id`)
    REFERENCES `goit`.`companies` (`company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_companies_has_projects_projects1`
    FOREIGN KEY (`projects_id`)
    REFERENCES `goit`.`projects` (`proj_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goit`.`projects_has_developers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goit`.`projects_has_developers` ;

CREATE TABLE IF NOT EXISTS `goit`.`projects_has_developers` (
  `projects_id` INT NOT NULL,
  `developers_id` INT NOT NULL,
  PRIMARY KEY (`projects_id`, `developers_id`),
  INDEX `fk_projects_has_developers_developers1_idx` (`developers_id` ASC),
  INDEX `fk_projects_has_developers_projects1_idx` (`projects_id` ASC),
  CONSTRAINT `fk_projects_has_developers_projects1`
    FOREIGN KEY (`projects_id`)
    REFERENCES `goit`.`projects` (`proj_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projects_has_developers_developers1`
    FOREIGN KEY (`developers_id`)
    REFERENCES `goit`.`developers` (`dev_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goit`.`companies_has_developers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goit`.`companies_has_developers` ;

CREATE TABLE IF NOT EXISTS `goit`.`companies_has_developers` (
  `companies_id` INT NOT NULL,
  `developers_id` INT NOT NULL,
  PRIMARY KEY (`companies_id`, `developers_id`),
  INDEX `fk_companies_has_developers_developers1_idx` (`developers_id` ASC),
  INDEX `fk_companies_has_developers_companies1_idx` (`companies_id` ASC),
  CONSTRAINT `fk_companies_has_developers_companies1`
    FOREIGN KEY (`companies_id`)
    REFERENCES `goit`.`companies` (`company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_companies_has_developers_developers1`
    FOREIGN KEY (`developers_id`)
    REFERENCES `goit`.`developers` (`dev_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `goit`.`customers_has_projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `goit`.`customers_has_projects` ;

CREATE TABLE IF NOT EXISTS `goit`.`customers_has_projects` (
  `customers_id` INT NOT NULL,
  `projects_id` INT NOT NULL,
  PRIMARY KEY (`customers_id`, `projects_id`),
  INDEX `fk_customers_has_projects_projects1_idx` (`projects_id` ASC),
  INDEX `fk_customers_has_projects_customers1_idx` (`customers_id` ASC),
  CONSTRAINT `fk_customers_has_projects_customers1`
    FOREIGN KEY (`customers_id`)
    REFERENCES `goit`.`customers` (`cust_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customers_has_projects_projects1`
    FOREIGN KEY (`projects_id`)
    REFERENCES `goit`.`projects` (`proj_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
